name: Bedwars1058-Leave-Delay
version: '${project.version}'
main: me.zuyte.leavedelay.Main
api-version: '1.13'
authors: [ Zuyte ]
description: adds leave delay to bedwars quit item
softdepend: [ BedWars1058 ]
commands:
  leavedelay:
    description: 'Reloads the leavedelay config'
    permission: 'bw.leavedelay'
permissions:
   bw.leavedelay:
    description: 'permission to use /leavedelay'
    default: OP